// http://www.homeandlearn.co.uk/java/java_combo_boxes.html

// NOTE THIS FILE DEPENDS ON THE PROJECT FROM SECTION 9



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form_controls_lesson;

// Button Group / Prompt Box
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

// File Explorer Filter (i.e. open txt, png, etc)
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;

// Import my own project from section 9
import textfiles.ReadFile;
import textfiles.WriteFile;

/** 
 *
 * @author tommy
 */
public class FormObjects extends javax.swing.JFrame {
    
    // Create a Button Group for Radio Buttons (so you can't select more than 1)
    private void groupButton() {

        ButtonGroup bg1 = new ButtonGroup( );

        bg1.add(jRadioButton1);
        bg1.add(jRadioButton2);
        bg1.add(jRadioButton3);

    }

    /**
     * Creates new form FormObjects
     */
    public FormObjects() {
        initComponents();
        
        // Intialize Button Group
        groupButton();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        db = new javax.swing.JFileChooser();
        comboOne = new javax.swing.JComboBox<>();
        btnComboBox = new javax.swing.JButton();
        txtComboBoxItem = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        btnCheckBoxes = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        taOne = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        btnRadios = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Coder Languages");

        comboOne.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Java", "Ruby", "NodeJS", "Python" }));

        btnComboBox.setText("Get Dropdown Item");
        btnComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComboBoxActionPerformed(evt);
            }
        });

        jCheckBox1.setText("Java");

        jCheckBox2.setText("Ruby");

        jCheckBox3.setText("NodeJS");

        jCheckBox4.setText("Python");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox1)
                    .addComponent(jCheckBox2)
                    .addComponent(jCheckBox3)
                    .addComponent(jCheckBox4))
                .addGap(12, 12, 12))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jCheckBox1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox4)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        btnCheckBoxes.setText("Selected Items");
        btnCheckBoxes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckBoxesActionPerformed(evt);
            }
        });

        taOne.setColumns(20);
        taOne.setRows(5);
        jScrollPane1.setViewportView(taOne);

        jRadioButton1.setText("Credit Card");

        jRadioButton2.setText("Debit Card");

        jRadioButton3.setText("PayPal");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton3))
                .addGap(0, 13, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jRadioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton3)
                .addGap(0, 19, Short.MAX_VALUE))
        );

        btnRadios.setText("Make Payment");
        btnRadios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRadiosActionPerformed(evt);
            }
        });

        jMenu1.setText("File");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Open");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Save");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRadios)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboOne, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnComboBox)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtComboBoxItem))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnCheckBoxes)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboOne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnComboBox)
                    .addComponent(txtComboBoxItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(btnCheckBoxes))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnRadios)
                        .addGap(48, 48, 48))))
        );

        pack();
    }// </editor-fold>                        

    private void btnComboBoxActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // Chosen dropdown item to appear in the text field
        String itemText = (String)comboOne.getSelectedItem( );
        txtComboBoxItem.setText( itemText );
    }                                           

    private void btnCheckBoxesActionPerformed(java.awt.event.ActionEvent evt) {                                              
        //  See if each box is selected or not
        String s1 = "";
        
        if (jCheckBox1.isSelected()) {
            s1 += " " + jCheckBox1.getText() + "\n";
        }
        
        if (jCheckBox2.isSelected()) {
            s1 += " " + jCheckBox2.getText() + "\n";
        }
        
        if (jCheckBox3.isSelected()) {
            s1 += " " + jCheckBox3.getText() + "\n";
        }
        
        if (jCheckBox4.isSelected()) {
            s1 += " " + jCheckBox4.getText() + "\n";
        }
        
        // Set the Text Area to the selected items
        taOne.setText(s1);
    }                                             

    private void btnRadiosActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // Display a message box stating which radio button was clicked
        String radioText = "";
        
        if (jRadioButton1.isSelected()) {
            radioText = jRadioButton1.getText();
        }
        
        else if (jRadioButton2.isSelected()) {
            radioText = jRadioButton2.getText();
        }
        
        else if (jRadioButton3.isSelected()) {
            radioText = jRadioButton3.getText();
        }
        else {
            radioText = "No Payment Option Selected!";
        }
        
        // Pop Up Message Box
        javax.swing.JOptionPane.showMessageDialog( FormObjects.this, radioText );
    }                                         

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        
        // Filter for only certain types of file
        FileFilter ft1 = new FileNameExtensionFilter("Text Files", "txt");
        FileFilter ft2 = new FileNameExtensionFilter("HTML Files", "html", "htm");
        db.addChoosableFileFilter( ft1 );
        db.addChoosableFileFilter( ft2 );
        
        // Check if user clicked OK on file selection
        int returnVal = db.showOpenDialog(this);
        
        // User clicked up on selected file
        if (returnVal == javax.swing.JFileChooser.APPROVE_OPTION) {
            java.io.File file = db.getSelectedFile();
            String file_name = file.toString( );
            
            try {
                ReadFile file_read = new ReadFile( file_name );
                String[] arrayLines = file_read.OpenFile();
                String theText = "";
                for (int i=0; i < arrayLines.length; i++) {
                    theText = theText + arrayLines[i] + "\n";
                }
                taOne.setText(theText);
            }
            catch (java.io.IOException e) {
                JOptionPane.showMessageDialog( FormObjects.this, "File Read Error! \n" + e );
            }

        }
        // User did not select a file
        else {
            JOptionPane.showMessageDialog( FormObjects.this, "No File Chosen." );
        }
    }                                          

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // Save the text in the text field to txt file
        FileFilter ft = new FileNameExtensionFilter( "Text Files", "txt" );
        db.addChoosableFileFilter( ft );
        int returnVal = db.showSaveDialog(this);
        
        if (returnVal == javax.swing.JFileChooser.APPROVE_OPTION) {
            java.io.File saved_file = db.getSelectedFile();
            String file_name = saved_file.toString();
            
            try {
                WriteFile data = new WriteFile(file_name, false);
                String allText = taOne.getText();
                data.writeToFile(allText);
            }
            catch (java.io.IOException e) {
                JOptionPane.showMessageDialog( FormObjects.this, "File Read Error! \n" + e );
            }
        }
        
        
    }                                          

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormObjects.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormObjects.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormObjects.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormObjects.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormObjects().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnCheckBoxes;
    private javax.swing.JButton btnComboBox;
    private javax.swing.JButton btnRadios;
    private javax.swing.JComboBox<String> comboOne;
    private javax.swing.JFileChooser db;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea taOne;
    private javax.swing.JTextField txtComboBoxItem;
    // End of variables declaration                   
}
